[workspace]
members = ["crates/*"]
resolver = "2"


[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
tokio = "1.43.0"
serde = { version = "1.0.218", features = ["derive"] }
reqwest = "0.12.12"
serde_json = "1.0.139"
